apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: go-test-rr-vv-gitops
  description: This is GitOps manifest for go-test-rr-vv   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: go-test-rr-vv
    janus-idp.io/tekton: go-test-rr-vv 
    backstage.io/kubernetes-id: go-test-rr-vv 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:go-test-rr-vv
