apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-test-rr-vv
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtaptestqa/test:1fbd600f16fc519e074118f19acdbcdbbdd0c668@sha256:2d109856a6d18f7c48ad198f6f1547dfe7cf5506750de458e4fd3ad07b99732a
          name: container-image
